### ISSUE TITLE
FRAM32 and read / write object

### ISSUE THREAD

**Issue by geologic** [RobTillaart/FRAM_I2C#42]
Hi

I'm using FRAM32 library on a MB85RC1MT to read/write STRUCT objects. When compiling i get this error:

undefined reference to `unsigned long FRAM32::readObject<LogDataStructure>(unsigned long, LogDataStructure&)'

The same for writeObject.

Can you please advise?

**Comment by RobTillaart** [comment]
Thanks for the issue, 
Will look into it tomorrow as today is "full".

**Comment by RobTillaart** [comment]
Could you check if you could read/writeObject of a simple datatype e.g int?

**Comment by RobTillaart** [comment]
Hypothesis
In the FRAM class the functions are implemented in .h
In the FRAM32 class the functions are in .cpp.

Moving the implementation to .h file miight solve it
Todo: write text sketch tomorrow

**Comment by RobTillaart** [comment]
Problem confirmed => BUG

**Comment by RobTillaart** [comment]
@geologic 
- Moving the template functions to the .h file solved the problem for AVR and ESP32.
- Created a develop branch and a PR for version 0.6.0
- Added two examples that use it for FRAM32 and FRAM11 (other derived class)

If you have time, could you verify the develop branch if it works for you?

**Comment by geologic** [comment]
Just to let you know that now it's working, thanks!

**Comment by RobTillaart** [comment]
Very important feedback!
