### ISSUE TITLE
Tested device: FM24C256-G (Ramtron) Works

### ISSUE THREAD

**Issue by ifreislich** [RobTillaart/FRAM_I2C#45]
Rob,

For your supported table: the Ramtron FM24C256-G works with this library. I'm using it in several projects and It's *much cheaper than the Fujitsu devices. Despite the datasheet stating Vcc=4.7-5.5V I've only ever used the device with an ESP32 and ESP8266 at 3.3V.

It does not have a device register so there's no device metadata.
It does not support sleep.

Standby current 100uA
Active current SCL=100kHz 200uA, SCL=400kHz 500uA, SCL=1MHz 1.2mA

**Comment by RobTillaart** [comment]
Super!
Thanks for this info / confirmation.
Will update documentation asap

**Comment by ifreislich** [comment]
It's 256kbit in 32k * 8.

**Comment by RobTillaart** [comment]
Sorry my mistake, will fix asap.

**Comment by ifreislich** [comment]
No worries. Thanks for a great library.
