### ISSUE TITLE
Bug with reading

### ISSUE THREAD

**Issue by ddprog** [RobTillaart/FRAM_I2C#51]
Hello!

I found a bug with reading from FRAM from the second half of the addresses (1 Mbit). Please look and correct.
![readblock](https://github.com/RobTillaart/FRAM_I2C/assets/84571634/23dfb75f-9adc-499e-9786-fa802d43eb8b)

**Comment by ddprog** [comment]
Corrected for _addr, it seems to read correctly.

**Comment by RobTillaart** [comment]
Thank you for reporting the bug. (not tested well enough apparently)

Code should indeed be:

```cpp
void FRAM32::_readBlock(uint32_t memAddr, uint8_t * obj, uint8_t size)
{
  uint8_t _addr = _address;
  if (memAddr & 0x00010000) _addr += 0x01;

  _wire->beginTransmission(_addr);
  _wire->write((uint8_t) (memAddr >> 8));
  _wire->write((uint8_t) (memAddr & 0xFF));
  _wire->endTransmission();
  _wire->requestFrom(_addr, size);
  uint8_t * p = obj;
  for (uint8_t i = size; i > 0; i--)
  {
    *p++ = _wire->read();
  }
}
```

Will create a PR asap.

**Comment by RobTillaart** [comment]
Develop branch + PR created

**Comment by RobTillaart** [comment]
#### Note
if memAddr would be e.g. 0x00020001,  would interfere with lower memory addresses too.
Robust guarding solves this too.

Note in readme.md future section to investigate error handling/ reporting wrt invalid memory addresses
