### ISSUE TITLE
FRAM size error

### ISSUE THREAD

**Issue by cynicalb** [RobTillaart/FRAM_I2C#54]
Rob

This FRAM is unsupported, I'm just reporting a result here. I have a MB85RC64A on a custom board.  It's 8,192 word s × 8 bits FRAM.  When I run sizeInBytes = FRAM.getSize() * 1024; it returns 0 bytes.  I will use the set function.

uint32_t framID = FRAM.getProductID() returns 4096 DEC. // The size of Device ID is 3 bytes and consists of manufacturer
ID and product ID. 

Regards

Jason

**Comment by RobTillaart** [comment]
Thanks for reporting,
I will keep the issue open and when time permits dive into the datasheet to check where/why .

**Comment by RobTillaart** [comment]
datasheet - https://www.fujitsu.com/us/Images/MB85RC64A-DS501-00019-2v0-E.pdf
does not mention a productID / device ID.

which label is on the device?
(from datasheet)
![image](https://github.com/RobTillaart/FRAM_I2C/assets/462844/a7fec82a-683c-4c38-8325-3fb65bf2a4fb)

**Comment by cynicalb** [comment]
My apologies, I see that I was working on the MB85RC64TA datasheet not the MB85RC64A which should be on my board.  You're right, the A version has no product or device ID.  

The plot thickens for me, I specified the MB85RC64A, but I have these markings, which is neither and I cannot find online. 
RC64A
E12214
   338

**Comment by RobTillaart** [comment]
Did some search and could not find the meaning either.

Most of the time these codes exist of a product code, a production date and batch number. 
RC64A is clearly the product code.
12214 could be a date, however the example in the datasheet 11000 does not look like it
338 and 300 could be batch codes. 

Some codes from the datasheets I have gave a little info
RC16 E11050 300
RC128A E11000 300
C64TA 11900 700

RC64V E11150 300  ---> different types can have same code.
RC256V E11150 300

RC256V E11150 300  ---> first digit after the E is the reel size for ordering. (1500, 2000)
RC256V E21200 300

RC1MT E11300 300

And then Yes more info!

RC04: Product name
E11900: E1(Environment code) + 1900(Year and Week code)
300: 3(Factory code) + 00(Trace code)

![image](https://github.com/RobTillaart/FRAM_I2C/assets/462844/e309bd7e-ea79-4889-8981-61fa40939af5)

Will add a line in the readme.md

**Comment by cynicalb** [comment]
Thanks again for going above and beyond.  I've followed your work for some time.  In fact, if I see that you've written a library, I'll use that in preference over all others because your work is very good.  Plus you've done a few blogs that I think are defining works for the topic.  Plus you're a gentleman on forums and so on.  A big thanks for your contributions to my work!

I'm comfortable to say that the MB85RC64A declared with the FRAM32 class has been tested working with:
void write8(uint16_t memAddr, uint8_t value) uint8_t
void write16(uint16_t memAddr, uint16_t value) uint16_t
void write32(uint16_t memAddr, uint32_t value) uint32_t

uint8_t read8(uint16_t memAddr)
uint16_t read16(uint16_t memAddr)
uint32_t read32(uint16_t memAddr

tested with struct and array
uint16_t writeObject(uint16_t memAddr, T &obj) 
uint16_t readObject(uint16_t memAddr, T &obj)

Jason

**Comment by RobTillaart** [comment]
>  A big thanks for your contributions to my work!

You're welcome

**Comment by cynicalb** [comment]
Rob

I wanted to send a gift but the payment failed.  Do you have a paypal
address that I can send it to?

Regards

Jason.

**Comment by RobTillaart** [comment]
Thanks for you generous donation!
